[package]
name = "chrome_server"
version = "0.1.8"
edition = "2021"
description = "Chrome proxy API to manage chrome in Cloud Providers"
license = "MIT"
repository = "https://github.com/spider-rs/chrome-server"

[dependencies]
hyper = "0.14.30"
lazy_static = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
warp = "0.3.6"
